### ISSUE TITLE
Pihole error: json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by blackbarn** [nlamirault/pihole_exporter#3]
`pihole-exporter    | time="2017-08-15T17:13:04Z" level=error msg="Pihole error: json: cannot unmarshal number into Go value of type string" source="pihole_exporter.go:143"`

Essentially the JSON is returning pihole counts as Numbers, yet the go struct used for the json defines them as Strings.

One would have to either have the pihole API return them as strings, or alter pihole_exporter to support `json.Number` I believe.

**Comment by bah2830** [comment]
This should be addressed in the lastest merge.
