### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by bah2830** [nlamirault/pihole_exporter#4]
Are you accepting PRs and would you be willing to add docker support? I use docker for nearly everything and run several exporters including this one in docker and would like to create a PR with the docker file. Didn't want to fork and start the PR if it's not something you wanted in the project.

**Comment by nlamirault** [comment]
Sure.

**Comment by bah2830** [comment]
Thank you, I have created https://github.com/nlamirault/pihole_exporter/pull/7.

Thanks for this useful project.
