### ISSUE TITLE
ERRO[0069] Pihole error: json: cannot unmarshal number into Go value of type string  source="pihole_exporter.go:143"

### ISSUE THREAD

**Issue by wjanes** [nlamirault/pihole_exporter#8]
Hi nlamirault

When i start the pihole_explorer i get the following error 

ERRO[0069] Pihole error: json: cannot unmarshal number into Go value of type string  source="pihole_exporter.go:143"

It seems that it has something to do with the pi_hole API

BR Wolfgang

**Comment by dr1s** [comment]
Hi Wolfgang,

I got the same issue with this exporter.

Go is not a language I understand, so I wrote my own exporter in Python 3. 
https://github.com/dr1s/pihole_exporter.py

Sorry for the shameless plug.

**Comment by nlamirault** [comment]
@wjanes could you try with the version of the develop branch ?

**Comment by wjanes** [comment]
Oh Hey, sorry for the late answer.   I will try it in the next few days when i will install pihole again. BR Wolfgang
